# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

variables:
  modifier_package_name: 'caliper-topdown'
  modifier_spack_variant: '+caliper'

modifiers:
  - name: caliper-topdown
    mode: topdown-all

software:
  packages:
    caliper-topdown:
      pkg_spec: caliper+adiak+mpi~libunwind~libdw+papi

