# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

packages:
  papi:
    externals:
    - spec: papi@6.0.0.1
      prefix: /usr/tce/packages/papi/papi-6.0.0.1
      buildable: false
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
    buildable: false
  cmake:
    externals:
    - spec: cmake@3.26.3
      prefix: /usr/tce/packages/cmake/cmake-3.26.3
    buildable: false
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr/tcetmp/packages/gmake/gmake-4.2.1
    buildable: false
  automake:
    externals:
    - spec: automake@1.16.1
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  python:
    externals:
    - spec: python@3.9.12
      prefix: /usr/tce/packages/python/python-3.9.12/
      buildable: false
  mpi:
    buildable: false
  mvapich2:
    buildable: false
    externals:
    - spec: mvapich2@2.3.7-gcc-11.2.1
      prefix: /usr/tce/packages/mvapich2/mvapich2-2.3.7-gcc-11.2.1
    - spec: mvapich2@2.3.7-intel-2021.6.0
      prefix: /usr/tce/packages/mvapich2/mvapich2-2.3.7-intel-classic-2021.6.0/
    - spec: mvapich2@2.3.7-clang-14.0.6
      prefix: /usr/tce/packages/mvapich2/mvapich2-2.3.7-clang-14.0.6
  cub:
    buildable: false
    externals:
    - spec: cub@11.8.0
      prefix: /usr/tce/packages/cuda/cuda-11.8.0/
  cuda:
    buildable: false
    externals:
    - spec: cuda@11.8.0
      prefix: /usr/tce/packages/cuda/cuda-11.8.0/
  curand:
    externals:
    - spec: curand@11.8.0
      prefix: /usr/tce/packages/cuda/cuda-11.8.0
    buildable: false
  cusparse:
    externals:
    - spec: cusparse@11.8.0
      prefix: /usr/tce/packages/cuda/cuda-11.8.0
    buildable: false
  cublas:
    externals:
    - spec: cublas@11.8.0
      prefix: /usr/tce/packages/cuda/cuda-11.8.0
    buildable: false
  blas:
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /usr/tce/packages/mkl/mkl-2022.1.0
    buildable: false
  fftw:
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /usr/tce/packages/mkl/mkl-2022.1.0
    buildable: false
  lapack:
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /usr/tce/packages/mkl/mkl-2022.1.0
    buildable: false
  intel-oneapi-mkl:
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /usr/tce/packages/mkl/mkl-2022.1.0/
    buildable: false
