# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: Pascal
  site: LLNL
  system: Penguin-broadwell-P100-OmniPath
  integrator:
    vendor: Penguin
    name:
  processor:
    vendor: Intel
    name: Xeon_E5-2695_v4
    ISA: x86_64
    uArch: broadwell
  accelerator:
    vendor: NVIDIA
    name: P100
    ISA: PTX
    uArch: sm_56
  interconnect:
    vendor: CornelisNetworks
    name: OmniPath
  system-tested:
    site: LLNL
    name: pascal
    installation-year: 2018
    description:
  top500-system-instances:
    -
