# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

compilers:
- compiler:
    spec: cce@16.0.0-rocm5.5.1
    paths:
      cc:  /opt/cray/pe/cce/16.0.0/bin/craycc
      cxx:  /opt/cray/pe/cce/16.0.0/bin/crayCC
      f77:  /opt/cray/pe/cce/16.0.0/bin/crayftn
      fc:  /opt/cray/pe/cce/16.0.0/bin/crayftn
    flags:
      cflags: -g -O2
      cxxflags: -g -O2 -std=c++14
      fflags: -g -O2 -hnopattern
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: [/opt/cray/pe/gcc-libs/]
- compiler:
    spec: gcc@12.2.0
    paths:
      cc: /opt/cray/pe/gcc/12.2.0/bin/gcc
      cxx: /opt/cray/pe/gcc/12.2.0/bin/g++
      f77: /opt/cray/pe/gcc/12.2.0/bin/gfortran
      fc: /opt/cray/pe/gcc/12.2.0/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
