# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: x86_64
  site:
  system: x86_64
  integrator:
    vendor:
    name:
  processor:
    vendor:
    name:
    ISA: x86_64
    uArch:
  accelerator:
    vendor:
    name:
    ISA:
    uArch:
  interconnect:
    vendor:
    name:
  system-tested:
    site:
    name:
    installation-year:
    description:
  top500-system-instances:
    -
