# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

variables:
  batch_time: ''
  pre_process: ''
  mpi_command: 'mpirun -n {n_nodes} -c {n_ranks} --oversubscribe'
  post_process: ''
  batch_submit: '{execute_experiment}'
  batch_nodes: ''
  batch_ranks: ''
  batch_timeout: ''
