packages:
  blas:
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /usr/tce/backend/installations/linux-rhel8-x86_64/intel-19.0.4/intel-oneapi-mkl-2022.1.0-sksz67twjxftvwchnagedk36gf7plkrp
      buildable: false
  lapack:
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /usr/tce/backend/installations/linux-rhel8-x86_64/intel-19.0.4/intel-oneapi-mkl-2022.1.0-sksz67twjxftvwchnagedk36gf7plkrp
      buildable: false
  mpi:
    externals:
    - spec: mvapich2@2.3.7-gcc12.1.1
      prefix: /usr/tce/packages/mvapich2/mvapich2-2.3.7-gcc-12.1.1
      buildable: false
      extra_attributes:
        ldflags: "-L/usr/tce/packages/mvapich2/mvapich2-2.3.7-gcc-12.1.1/lib -lmpi"
    - spec: mvapich2@2.3.7-intel2021.6.0-classic
      prefix: /usr/tce/packages/mvapich2/mvapich2-2.3.7-intel-classic-2021.6.0
      buildable: false
      extra_attributes:
        ldflags: "-L/usr/tce/packages/mvapich2/mvapich2-2.3.7-intel-classic-2021.6.0/lib -lmpi"
