# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

packages:
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
      buildable: false
  cmake:
    externals:
    - spec: cmake@3.23.1
      prefix: /usr/tce/packages/cmake/cmake-3.23.1
      buildable: false
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  blas:
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /usr/tce/backend/installations/linux-rhel8-x86_64/intel-19.0.4/intel-oneapi-mkl-2022.1.0-sksz67twjxftvwchnagedk36gf7plkrp
      buildable: false
  lapack:
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /usr/tce/backend/installations/linux-rhel8-x86_64/intel-19.0.4/intel-oneapi-mkl-2022.1.0-sksz67twjxftvwchnagedk36gf7plkrp
      buildable: false
  python:
    externals:
    - spec: python@3.9.12
      prefix: /usr/tce/packages/python/python-3.9.12/
      buildable: false
  hwloc:
    externals:
    - spec: hwloc@2.9.1
      prefix: /usr
      buildable: false
  fftw:
    externals:
    - spec: fftw@3.3.10
      prefix: /usr/tce/packages/fftw/fftw-3.3.10
      buildable: false
  mpi:
    externals:
    - spec: mvapich2@2.3.7-gcc1211
      prefix: /usr/tce/packages/mvapich2/mvapich2-2.3.7-gcc-12.1.1
      buildable: false
      extra_attributes:
        ldflags: "-L/usr/tce/packages/mvapich2/mvapich2-2.3.7-gcc-12.1.1/lib -lmpi"
    - spec: mvapich2@2.3.7-intel202160classic
      prefix: /usr/tce/packages/mvapich2/mvapich2-2.3.7-intel-classic-2021.6.0
      buildable: false
      extra_attributes:
        ldflags: "-L/usr/tce/packages/mvapich2/mvapich2-2.3.7-intel-classic-2021.6.0/lib -lmpi"
