# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

system_definition:
  name: Magma
  site: LLNL
  system: Penguin-icelake-OmniPath
  integrator:
    vendor: PenguinComputing
    name: RelionCluster
  processor:
    vendor: Intel
    name: XeonPlatinum924248C
    ISA: x86_64
    uArch: icelake
  accelerator:
    vendor:
    name:
    ISA:
    uArch:
  interconnect:
    vendor: CornelisNetworks
    name: OmniPath
  system-tested:
    site: LLNL
    name: magma
    installation-year: 2019
    description: top500 <https://www.top500.org/system/179774>
  top500-system-instances:
    - Magma (LLNL)
