packages:
  all:
    compiler: [gcc@12.2.0]
    target: [zen2]
    providers:
      mpi: [cray-mpich@8.1.27]
      blas: [openblas,cray-libsci@23.09.1.1]
      lapack: [openblas,cray-libsci@23.09.1.1]
      scalapack: [netlib-scalapack,cray-libsci@23.09.1.1]
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.27%gcc
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/gnu/9.1
      modules:
      - libfabric/1.15.2.0
    - spec: cray-mpich@8.1.27%cce
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/cray/14.0
      modules:
      - libfabric/1.15.2.0
    - spec: cray-mpich@8.1.27%rocmcc
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/amd/5.0
      modules:
      - libfabric/1.15.2.0
    buildable: false
  cray-libsci:
    externals:
    - spec: cray-libsci@23.09.1.1%gcc
      prefix: /opt/cray/pe/libsci/23.09.1.1/gnu/10.3/x86_64
      modules:
      - cray-libsci/23.09.1.1
    - spec: cray-libsci@23.09.1.1%cce
      prefix: /opt/cray/pe/libsci/23.09.1.1/cray/12.0/x86_64
      modules:
      - cray-libsci/23.09.1.1
    - spec: cray-libsci@23.09.1.1%rocmcc
      prefix: /opt/cray/pe/libsci/23.09.1.1/AMD/5.0/x86_64
      modules:
      - cray-libsci/23.09.1.1
    buildable: false
  gcc:
    externals:
    - spec: gcc@7.5.0 languages=c,c++,fortran
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++-7
          fortran: /usr/bin/gfortran
  slurm:
    externals:
    - spec: slurm@22.05.10
      prefix: /usr
    buildable: false
  comgr:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: comgr@5.6.1
  hip:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/hip
      spec: hip@5.6.1
  hip-rocclr:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/rocclr
      spec: hip-rocclr@5.6.1
  hipblas:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: hipblas@5.6.1
  hipcub:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: hipcub@5.6.1
  hipfft:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: hipfft@5.6.1
  hipfort:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: hipfort@5.6.1
  hipify-clang:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: hipify-clang@5.6.1
  hipsparse:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: hipsparse@5.6.1
  hsa-rocr-dev:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: hsa-rocr-dev@5.6.1
  hsakmt-roct:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: hsakmt-roct@5.6.1
  llvm-amdgpu:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/llvm
      spec: llvm-amdgpu@5.6.1
  rccl:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rccl@5.6.1
  rocalution:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocalution@5.6.1
  rocblas:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocblas@5.6.1
  rocfft:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocfft@5.6.1
    variants: amdgpu_target=auto amdgpu_target_sram_ecc=auto
  rocm-clang-ocl:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocm-clang-ocl@5.6.1
  rocm-cmake:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocm-cmake@5.6.1
  rocm-device-libs:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocm-device-libs@5.6.1
  rocm-gdb:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocm-gdb@5.6.1
  rocm-opencl:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/opencl
      spec: rocm-opencl@5.6.1
  rocm-opencl-runtime:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/opencl
      spec: rocm-opencl-runtime@5.6.1
  rocm-openmp-extras:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/llvm
      spec: rocm-openmp-extras@5.6.1
  rocm-smi:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/rocm_smi
      spec: rocmsmi@5.6.1
  rocm-smi-lib:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/rocm_smi
      spec: rocm-smi-lib@5.6.1
  rocminfo:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocminfo@5.6.1
  rocprim:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocprim@5.6.1
  rocprofiler-dev:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocprofiler-dev@5.6.1
  rocrand:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocrand@5.6.1
  rocsolver:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocsolver@5.6.1
  rocsparse:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocsparse@5.6.1
  rocthrust:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: rocthrust@5.6.1
  roctracer-dev:
    buildable: false
    externals:
    - prefix: /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1
      spec: roctracer-dev@5.6.1
